stages:
  - build # build googletests & tests, artifact tests (why dont run?)
  - test # run tests
  - deploy
  - package
  - package-test

variables:
  GIT_SUBMODULE_STRATEGY: none
  GIT_SUBMODULE_DEPTH: 1

#
# BUILD
#
build-job-ubuntu:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - g++ --version
    - sudo apt update && sudo apt upgrade
    - sudo apt install gcc
    - g++ --version
    - ls googletest/
    # on ubuntu submodule is NOT copied for some reason
    # so we need to clone it manually
    #
    # on ubuntu g++ is lower c++17 so we need to fetch old version of googletest
    - rm -rf googletest/
    - git clone -b v1.15.x https://github.com/google/googletest.git 
    - cd googletest
    # - git checkout v1.15.x 
    - mkdir build 
    - cd build
    - cmake ..
    - cmake --build . -j8
    - mv lib ../../gtest/lib
    - cd ../..
  script:
    - make all CFLAGS=--std=c++17
    - mv basic_test basic_test_ubuntu
    - mv calculation_test calculation_test_ubuntu
  tags:
    - ubuntu
  artifacts:
    paths:
      - basic_test_ubuntu
      - calculation_test_ubuntu

build-job-centos:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - g++ --version
    - ls googletest/
    # on CentOS submodule is copied with original repository
    # - git clone https://github.com/google/googletest.git 
    - cd googletest
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . -j8
    - mv lib ../../gtest/lib
    - cd ../..
  script:
    - make all
    - mv basic_test basic_test_centos
    - mv calculation_test calculation_test_centos
  tags:
    - centos
  artifacts:
    paths:
      - basic_test_centos
      - calculation_test_centos



#
# TEST
#
test-job-ubuntu:
  stage: test
  # dependencies: [build-job-ubuntu] 
  needs: 
    - job: build-job-ubuntu
      artifacts: true
  script:
    - ls
    - valgrind ./basic_test_ubuntu
    - valgrind ./calculation_test_ubuntu
  tags:
    - ubuntu

test-job-centos:
  stage: test
  # dependencies: [build-job-centos]
  needs: 
    - job: build-job-centos
      artifacts: true 
  script:
    - ls
    - valgrind ./basic_test_centos
    - valgrind ./calculation_test_centos
  tags:
    - centos


#
# DEPLOY
#
deploy-documentation-job:
  stage: deploy
  dependencies: []
  before_script:
    - ls
    - apt-get -y install doxygen
  script: 
    - doxygen
    - ls
    - ls doxygen
  artifacts:
    name: "Documentation $CI_COMMIT_REF_SLUG/$CI_COMMIT_SHORT_SHA"
    paths:
      - "doxygen/**"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "gitlab-ci-test"
    - if: $CI_COMMIT_TAG
  tags:
    - ubuntu

deploy-prod-job:
  stage: deploy
  # dependencies: [] 
  # dependencies: [deploy-documentation-job] 
  needs: 
    - job: deploy-documentation-job
      artifacts: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - ls
    - release-cli -v
  script: 
    # - rm -rf gtest googletest test matrices Makefile Doxyfile
    - ls
    - ls doxygen
    - echo "Deploying..."
    - release-cli create
      --name "Release $CI_COMMIT_REF-$CI_COMMIT_SHORT_SHA"
      --tag_name "$CI_COMMIT_REF"
      --ref "$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
      --description "$CI_COMMIT_MESSAGE"
      --assets-links "{\"name\":\"Documentation\", \"url\":\"https://vgit.mirea.ru/s7k/agoev_matrix/-/jobs/$CI_JOB_ID/artifacts/download\"}"
  artifacts:
    name: "Release $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - "doxygen/**"
  # release:
  #   name: 'Release $CI_COMMIT_REF-$CI_COMMIT_SHORT_SHA'
  #   tag_name: '$CI_COMMIT_REF'
  #   ref: '$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA'
  #   description: '$CI_COMMIT_MESSAGE'
  #   assets:
  #     links:
  #       - name: 'Documentation'
  #         url: 'https://vgit.mirea.ru/s7k/agoev_matrix/-/jobs/$CI_JOB_ID/artifacts/download'
  #         # https://vgit.mirea.ru/s7k/agoev_matrix/-/jobs/75472/artifacts/download
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_COMMIT_BRANCH == "gitlab-ci-test"
    - if: $CI_COMMIT_TAG =~ "/gitlab-ci-test-*/gm"
      when: never
    - if: $CI_COMMIT_TAG
  tags:
    - ubuntu