stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - package
  - package-test

build-job-ubuntu:
  stage: build
  script:
    - mkdir bin
    - g++ ./test/basic-test.cpp -I./gtest/include -lgtest -o basic_test
  tags:
  artifacts:
    paths:
      - basic_test

build-job-centos:
  stage: build
  script:
    - mkdir bin
    - g++ ./test/basic-test.cpp -I./gtest/include -lgtest -o basic_test
  tags:
    - centos
  artifacts:
    paths:
      - basic_test
    
test-job-ubuntu:
  stage: test
  script:
    - ./basic_test
  tags:
    - ubuntu

test-job-centos:
  stage: test
  script:
    - ./basic_test
  tags:
    - centos