stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - package
  - package-test

build-job-ubuntu:
  stage: build
  before_script:
    - cd googletest
    - ls -a -l
    - cmake ../googletest
    - cmake --build . -j8
    - mv lib ../gtest/lib
    - cd ..
  script:
    - mkdir bin
    - g++ ./test/basic-test.cpp -I./gtest/include -L./gtest/lib -lgtest -o basic_test
  tags:
    - ubuntu
  artifacts:
    paths:
      - basic_test

build-job-centos:
  stage: build
  before_script:
    - mkdir build 
    - cd build
    - cmake ../googletest
    - cmake --build . -j8
    - mv lib ../gtest/lib
    - cd ..
  script:
    - mkdir bin
    - g++ ./test/basic-test.cpp -I./gtest/include -L./gtest/lib -lgtest -o basic_test
  tags:
    - centos
  artifacts:
    paths:
      - basic_test






test-job-ubuntu:
  stage: test
  script:
    - ./basic_test
  tags:
    - ubuntu

test-job-centos:
  stage: test
  script:
    - ./basic_test
  tags:
    - centos